### ISSUE TITLE
more info about poses.txt and ranges.txt file

### ISSUE THREAD

**Issue by afazel** [jbonnett92/CPlusPluss-Assignment-One#1]
Can you please let me know what are the columns in poses.txt and ranges.txt?
I believe poses.txt contains [robotX,robotY,robotTheta] and each line belong to one timestamp, is that correct? How about ranges.txt?

**Comment by jbonnett92** [comment]
Hi @afazel 
Yes you are correct, the ranges.txt contains the sensor values each line belongs to one timestamp too. We were not told what sensor they were or where they were on the robot, although that didn't matter in our case.

I treated each one as a distance sensor and spaced them out evenly around the robot by adding a yaw value to the sensor object. You can see the code that does that [here](https://github.com/jbonnett92/CPlusPluss-Occupancy-Grid/blob/master/Robot.cpp#L239). See the second parameter.

Jamie

**Comment by jbonnett92** [comment]
Could I ask what you're working on? I seen that you had questions about multiple occupancy grid projects.
